### PR TITLE
"copy" option to force copy files instead of symlink

### PR DESCRIPTION
**Pull request by rodrigosetti**

### CODE REVIEW

**Comment by rwjblue** [comment]
Thanks for the PR! Could you add tests to help me make sure this doesn't break in the future?

**Comment by rodrigosetti** [comment]
@rwjblue ok to merge?

**Comment by rwjblue** [comment]
`symlinkOrCopySync` encapsulates the copying logic for windows. No changes should be needed.

**Comment by rodrigosetti** [comment]
This change is about to have a way to force "copy", because by default it will symlink. There are some use cases that one would like not to symlink, but copy.

**Comment by rwjblue** [comment]
Hmm, why would you not want to symlink?

**Comment by rodrigosetti** [comment]
in my case, I'm using your plugin copy a lot of tests fixtures (of database files), that gets modified by the application when running the tests - so before each tests I want to get a "clean" set of files.

I guess in the general pattern, if one wants to modify the files without changing the originals then symlink will not do.

**Comment by rwjblue** [comment]
You should never modify the input tree of any broccoli plugin.  If you need to modify, your plugin should read the input, and output the modification (to a new file on disk).

**Pull request closed without merging**
